basePath: /
host: localhost:8080
info:
  contact:
    email: jonathan.bravo@ufl.edu
    name: API Support
  description: API documentation for the Front Runner application.
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Front Runner API
  version: "1.0"
paths:
  /api/data/image/{filename}:
    get:
      description: Fetches an image if it exists and they are authorized.
      parameters:
      - description: Filepath of image
        in: path
        name: filename
        required: true
        type: string
      produces:
      - image/*
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: User is not logged in
          schema:
            type: string
        "403":
          description: Permission denied
          schema:
            type: string
        "404":
          description: Requested image does not exist
          schema:
            type: string
        "500":
          description: Unable to retrieve User ID
          schema:
            type: string
      summary: Retrive an image
      tags:
      - images
  /api/data/upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads an image if the user is authorized.
      parameters:
      - description: Filepath of image
        in: formData
        name: filename
        required: true
        type: file
      responses:
        "200":
          description: Filename of uploaded image
          schema:
            type: string
        "401":
          description: User is not logged in
          schema:
            type: string
        "403":
          description: Permission denied
          schema:
            type: string
        "404":
          description: Requested image does not exist
          schema:
            type: string
        "415":
          description: Invalid file type
          schema:
            type: string
        "500":
          description: File already exists
          schema:
            type: string
      summary: Upload an image
      tags:
      - images
  /api/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authenticates a user and creates a session.
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Logged in successfully.
          schema:
            type: string
        "400":
          description: Email and password are required
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            type: string
      summary: User login
      tags:
      - authentication
      - login
  /api/logout:
    post:
      description: Logs out the current user by clearing the session.
      produces:
      - text/plain
      responses:
        "200":
          description: Logged out successfully
          schema:
            type: string
      summary: User logout
      tags:
      - authentication
      - logout
  /api/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Registers a new user using email, password, and an optional business
        name.
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      - description: Business name
        in: formData
        name: business_name
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Email and password are required or invalid email format
          schema:
            type: string
        "409":
          description: Email already in use or database error
          schema:
            type: string
      summary: Register a new user
      tags:
      - authentication
      - user
      - dbtable
  /api/validemail:
    get:
      description: Checks if the provided email address is in a valid format. Returns
        true if valid, false otherwise.
      parameters:
      - description: Email address to validate
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: true if email is valid, false otherwise
          schema:
            type: boolean
      summary: Validate email address
      tags:
      - utility
      - email
      - validate
swagger: "2.0"
